// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232.Lab1.CoffeeStore.Repositories.Context;

#nullable disable

namespace PRN232.Lab1.CoffeeStore.Repositories.Migrations
{
    [DbContext(typeof(CoffeeStoreContext))]
    partial class CoffeeStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRN232.Lab1.CoffeeStore.Repositories.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__19093A0B273C077A");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Các loại cà phê",
                            Name = "Coffee"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Các loại trà",
                            Name = "Tea"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Bánh ngọt ăn kèm",
                            Name = "Pastry"
                        });
                });

            modelBuilder.Entity("PRN232.Lab1.CoffeeStore.Repositories.Models.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuId"));

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MenuId")
                        .HasName("PK__Menu__C99ED2303AC1AEF1");

                    b.ToTable("Menu", (string)null);

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            FromDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Morning Menu",
                            ToDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuId = 2,
                            FromDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Afternoon Menu",
                            ToDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PRN232.Lab1.CoffeeStore.Repositories.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__B40CC6CDE34F205E");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Product_CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Cà phê đậm đặc, vị mạnh",
                            Name = "Espresso",
                            Price = 30000m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Cà phê sữa bọt",
                            Name = "Cappuccino",
                            Price = 40000m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Cà phê sữa nóng",
                            Name = "Latte",
                            Price = 45000m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Trà xanh truyền thống",
                            Name = "Green Tea",
                            Price = 25000m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Trà đen nguyên chất",
                            Name = "Black Tea",
                            Price = 20000m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            Description = "Bánh sừng bò bơ",
                            Name = "Croissant",
                            Price = 35000m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "Bánh muffin socola",
                            Name = "Muffin",
                            Price = 30000m
                        });
                });

            modelBuilder.Entity("PRN232.Lab1.CoffeeStore.Repositories.Models.ProductInMenu", b =>
                {
                    b.Property<int>("ProductInMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductInMenuId"));

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductInMenuId")
                        .HasName("PK__ProductI__BAC4646B0E681553");

                    b.HasIndex(new[] { "MenuId" }, "IX_ProductInMenu_MenuId");

                    b.HasIndex(new[] { "ProductId", "MenuId" }, "UQ_Product_Menu")
                        .IsUnique();

                    b.ToTable("ProductInMenu", (string)null);

                    b.HasData(
                        new
                        {
                            ProductInMenuId = 1,
                            MenuId = 1,
                            ProductId = 1,
                            Quantity = 50
                        },
                        new
                        {
                            ProductInMenuId = 2,
                            MenuId = 1,
                            ProductId = 2,
                            Quantity = 50
                        },
                        new
                        {
                            ProductInMenuId = 3,
                            MenuId = 1,
                            ProductId = 4,
                            Quantity = 40
                        },
                        new
                        {
                            ProductInMenuId = 4,
                            MenuId = 1,
                            ProductId = 6,
                            Quantity = 20
                        },
                        new
                        {
                            ProductInMenuId = 5,
                            MenuId = 2,
                            ProductId = 3,
                            Quantity = 40
                        },
                        new
                        {
                            ProductInMenuId = 6,
                            MenuId = 2,
                            ProductId = 5,
                            Quantity = 30
                        },
                        new
                        {
                            ProductInMenuId = 7,
                            MenuId = 2,
                            ProductId = 7,
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("PRN232.Lab1.CoffeeStore.Repositories.Models.Product", b =>
                {
                    b.HasOne("PRN232.Lab1.CoffeeStore.Repositories.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PRN232.Lab1.CoffeeStore.Repositories.Models.ProductInMenu", b =>
                {
                    b.HasOne("PRN232.Lab1.CoffeeStore.Repositories.Models.Menu", "Menu")
                        .WithMany("ProductInMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductInMenu_Menu");

                    b.HasOne("PRN232.Lab1.CoffeeStore.Repositories.Models.Product", "Product")
                        .WithMany("ProductInMenus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductInMenu_Product");

                    b.Navigation("Menu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PRN232.Lab1.CoffeeStore.Repositories.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PRN232.Lab1.CoffeeStore.Repositories.Models.Menu", b =>
                {
                    b.Navigation("ProductInMenus");
                });

            modelBuilder.Entity("PRN232.Lab1.CoffeeStore.Repositories.Models.Product", b =>
                {
                    b.Navigation("ProductInMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
